spring:
  application:
    name: gft-rename
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
